[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 160000000L
lib_deps = olikraus/U8g2@^2.35.4
         h2zero/NimBLE-Arduino@^1.4.1
board_build.ino_dir = .
board_build.partitions = no_ota.csv
build_flags = -Os
